# Generated by Django 5.1.7 on 2025-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aadhar_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
